language: node_js
node_js:
- '6'
cache:
  yarn: true
install:
- npm i
script:
- npm run lint
- npm run codacy
before_deploy:
- npm run build
deploy:
  provider: npm
  email: bartosz.polanczyk@gmail.com
  api_key:
    secure: vTJLeHIzOzeu0mmKG10hWK8Cf6QctxtkLfRaBF73/UcdintMO8+CWWyiCtgUEQm3vRCaUZXBiu4xUPVigcUg3keZ4QaBbPZbn665L69GLzfLJLTknLG8ENVCWgM2wHIqHsJL9WLV47x4qeQW0Z8CPfLWpXytst/w6mL0GYeahQDtxKW/4m/RcTqCEeqt/03hLeUxAcUNnnxcqIakxQBNJbhR0uFswgTEtjoWrxrpSxA9Tuprdko7748m1fFGxl9DTjCcorWJuZW9V20FItyWwiSORjtXYyHscpAAQmrMvzfKFgP0NSIxw8L9aCucmxIgV9fHnyIZOlanYitfXvVOPoyslOiRFtBNt/1uqoSK9YKEfXh8WCqoYAnHexhXlUNREwZzRpdIPFjcA7gP8qQyvEYQVnM143Y1mbx7/ZMWhidcsF9MRnXQ6huMbJHoWvQH2V1Tg8vd0MwUoz+KUmuCAajwzCDrmd9UAzbrlPRlAXKhoc9tNsRsc0X0vk1CUW+nbdZpSXFaDlXeYuDWSWojdoU2nBr8iwSci4RYpQ5rn1V86aAfBKcTi435zTnCSRWHLBGyNL28meHUz4SJgSpZ4JTbdFi1e+clm8yrkbXR2rhOMrEeYcIL3SBsZl4LPqDMIdVbGzMGkg/0saCmxWhbkAOn51hyNvoz+tFH+gxqb5Y=
  on:
    branch: master
  skip_cleanup: true
